apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compact
  namespace: monitoring
  labels:
    app: thanos-compact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-compact
  template:
    metadata:
      labels:
        app: thanos-compact
    spec:
      containers:
      - name: thanos
        image: quay.io/thanos/thanos:v0.16.0
        args:
        - compact
        # - --log.level=debug
        - --data-dir=/data
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --wait
        env:
          - name: OBJSTORE_CONFIG
            valueFrom:
              secretKeyRef:
                name: objects-thanos
                key: objects.properties
        ports:
        - name: http
          containerPort: 10902
        livenessProbe:
          httpGet:
            port: 10902
            path: /-/healthy
        readinessProbe:
          httpGet:
            port: 10902
            path: /-/ready
