apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  namespace: monitoring
  labels:
    app: thanos-store-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store-gateway
  serviceName: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      containers:
      - name: thanos
        image: quay.io/thanos/thanos:v0.16.0
        args:
        - store
        # - --log.level=debug
        - --data-dir=/data
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --index-cache-size=500MB
        - --chunk-pool-size=500MB
        env:
          - name: OBJSTORE_CONFIG
            valueFrom:
              secretKeyRef:
                name: objects-thanos
                key: objects.properties
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        livenessProbe:
          httpGet:
            port: 10902
            path: /-/healthy
        readinessProbe:
          httpGet:
            port: 10902
            path: /-/ready           
